language: python
python:
  - "3.6"
cache: pip
install:
  - pip install -r nltk_api/requirements.txt
  - python -W ignore -m nltk.downloader wordnet punkt averaged_perceptron_tagger
script:
  - nosetests